package net.supersnetwork.fabric_utility;

import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.WorldSavePath;
import net.minecraft.world.World;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public final class WorldHeightManager {
    private static final String PACK_NAME = "fabric_utility_world_height";
    private static int lastWrittenRule = Integer.MIN_VALUE;
    private static Path lastPackRoot;
    private static int ticks;

    private WorldHeightManager() {
    }

    public static void register() {
        ServerLifecycleEvents.SERVER_STARTED.register(server -> synchronizePack(server, true));
        ServerTickEvents.END_SERVER_TICK.register(server -> {
            if (++ticks >= 100) {
                ticks = 0;
                synchronizePack(server, false);
            }
        });
    }

    private static void synchronizePack(MinecraftServer server, boolean startupCheck) {
        World overworld = server.getOverworld();
        if (overworld == null) {
            return;
        }

        int rule = overworld.getGameRules().getInt(FabricUtilityGameRules.WORLD_HEIGHT_LIMIT);
        Path packRoot = server.getSavePath(WorldSavePath.DATAPACKS).resolve(PACK_NAME);
        if (rule == lastWrittenRule && packRoot.equals(lastPackRoot)) {
            return;
        }
        lastWrittenRule = rule;
        lastPackRoot = packRoot;

        try {
            if (rule < 0) {
                removeGeneratedPack(packRoot);
                if (!startupCheck) {
                    FabricUtility.LOGGER.info("World height now inherits the active dimension type after the next server restart.");
                }
                return;
            }

            int requestedAddition = Math.min(rule, 1712);
            int alignedAddition = ((requestedAddition + 15) / 16) * 16;
            int dimensionHeight = 384 + alignedAddition;
            writeGeneratedPack(packRoot, dimensionHeight);

            if (rule != alignedAddition) {
                FabricUtility.LOGGER.warn(
                        "World height additions must align to 16-block sections; requested {}, generated {}.",
                        rule,
                        alignedAddition
                );
            }
            FabricUtility.LOGGER.info(
                    "Generated Overworld height datapack for max Y {}. Restart the server to apply dimension-height changes.",
                    320 + alignedAddition
            );
        } catch (IOException exception) {
            FabricUtility.LOGGER.error("Failed to update generated world-height datapack", exception);
        }
    }

    private static void writeGeneratedPack(Path packRoot, int dimensionHeight) throws IOException {
        Path dimensionType = packRoot.resolve("data").resolve("minecraft").resolve("dimension_type");
        Files.createDirectories(dimensionType);
        Files.writeString(packRoot.resolve("pack.mcmeta"), """
                {
                  "pack": {
                    "pack_format": 15,
                    "description": "Generated by Fabric Utility for the world-height gamerule"
                  }
                }
                """);
        Files.writeString(dimensionType.resolve("overworld.json"), """
                {
                  "ultrawarm": false,
                  "natural": true,
                  "coordinate_scale": 1.0,
                  "has_skylight": true,
                  "has_ceiling": false,
                  "ambient_light": 0.0,
                  "piglin_safe": false,
                  "bed_works": true,
                  "respawn_anchor_works": false,
                  "has_raids": true,
                  "min_y": -64,
                  "height": %d,
                  "logical_height": %d,
                  "infiniburn": "#minecraft:infiniburn_overworld",
                  "effects": "minecraft:overworld",
                  "monster_spawn_block_light_limit": 0,
                  "monster_spawn_light_level": {
                    "type": "minecraft:uniform",
                    "value": {
                      "min_inclusive": 0,
                      "max_inclusive": 7
                    }
                  }
                }
                """.formatted(dimensionHeight, dimensionHeight));
    }

    private static void removeGeneratedPack(Path packRoot) throws IOException {
        Files.deleteIfExists(packRoot.resolve("data").resolve("minecraft").resolve("dimension_type").resolve("overworld.json"));
        Files.deleteIfExists(packRoot.resolve("data").resolve("minecraft").resolve("dimension_type"));
        Files.deleteIfExists(packRoot.resolve("data").resolve("minecraft"));
        Files.deleteIfExists(packRoot.resolve("data"));
        Files.deleteIfExists(packRoot.resolve("pack.mcmeta"));
        Files.deleteIfExists(packRoot);
    }
}
